---
- hostname: LEAF01 
  hw_model: vEOS
  eos: EOS-4.17.8M
  snmp_location: KVM-NETPEF-H
  system_mac_address: 525400B209F0
  hostname_mgmt_ip: 192.168.100.103/24
  hostname_mgmt_mac: "08:00:27:dc:c4:2a"
  domian_id: vEOS-LAB
  topology:
   - neighborDevice: spine01.lab.ecmwf.int
     port: "Ethernet4"
     neighborPort: "Ethernet1"
     validation: none
   - neighborDevice: spine02.lab.ecmwf.int
     port: "Ethernet5"
     neighborPort: "Ethernet1"
     validation: none
   - neighborDevice: leaf02.lab.ecmwf.int
     port: "Ethernet6"
     neighborPort: "Ethernet6"
     validation: none
   - neighborDevice: leaf02.lab.ecmwf.int
     port: "Ethernet7"
     neighborPort: "Ethernet7"
     validation: none
  mlag_name: "mlag-vlan"
  mlag_ip: 10.0.0.1/24
  mlag_peer_ip: 10.0.0.2/24
  mlah_vlan: 4094
  peer_con:
   - port: Eth6
     desc: "Peer-Link-Leaf02 E6 Po6"
   - port: Rth7
     desc: "Peer-Link-Leaf02 E7 Po6"
  peer_con_po: 6
  spine_con:
   - port: Eth4
     desc: "Spine-Link-Spine01 Eth1"
     ip: 172.16.11.2/30
   - port: Eth5
     desc: "Spine-Link-Spine02 Eth1"
     ip: 172.16.21.2/30
  loopback:
   - int: 0
     desc: leaf01-id
     ip: 10.0.2.1/32

