---
 - name: Check arp-table file
   hosts: local
   tasks:
   #- file: path=/vagrant/NetAutomation/Ansible/LAB/ConfigRepos/reports/arp_table.csv state=absent
   - file: path=/vagrant/NetAutomation/Ansible/LAB/ConfigRepos/reports/arp_table.csv state=touch

 - name: Check ARP table on switch
   hosts: veos-lab
   tasks:
   - eos_command:
       commands: "show arp | json"
       provider: "{{ eos_connection }}"
     register: result
   - debug: var=result
   - set_fact: arp_table="{{ result.stdout[0].ipV4Neighbors }}"
   - lineinfile:
       dest:   /vagrant/NetAutomation/Ansible/LAB/ConfigRepos/reports/arp_table.csv
       regexp: "^{{inventory_hostname}},{{item['interface']}},{{item['address']}}"
       line:   "{{inventory_hostname}},{{item['interface']}},{{item['address']}},{{item['hwAddress']}}"
     with_items: "{{arp_table}}"

