---
ansible_device_os: nxos

cli:
  username:  "{{ansible_user}}"
  password:  "{{ansible_ssh_password|default(ansible_password)}}"
  host:      "{{ansible_host|default(inventory_hostname)}}"
  transport: cli

nxapi:
  username:  "{{ansible_user}}"
  password:  "{{ansible_ssh_password|default(ansible_password)}}"
  host:      "{{ansible_host|default(inventory_hostname)}}"
  transport: nxapi